name: yuehua
version: '1.0.0'
main: com.xiaoxiaoowo.yuehua.Yuehua
api-version: '1.20'
depend: [NBTAPI]
commands:
  advancement:
    description: advancement
  a:
    description: a
  check:
    description: check
  r:
    description: r
  blocktp:
    description: blocktp
  duanzao:
    description: duanzao
  intogame:
    description: intogame
  markrelife:
    description: markrelife
  mybossspawn:
    description: mybossspawn
  myspawn:
    description: myspawn
  relife:
    description: relife
  renou:
    description: renou
  renou2:
    description: renou2
  renou3:
    description: renou3
  select:
    description: select
  storerelifestone:
    description: storerelifestone
  datacountget:
    description: datacountget
  dataget:
    description: dataget
  dataset:
    description: dataget
  itemdataget:
    description: itemdata
  clearup:
    description: clearup
  mysave:
    description: mysave
  gi:
    description: gi
    aliases:
      - GI
      - gI
      - Gi
  mytp:
    description: mytp
  perget:
    description: perget
  setsign:
    description: setsign
  mysummon:
    description: mysummon
  buy:
    description: buy
  sell:
    description: sell
  sale:
    description: sale
  yhteam:
    description: yhteam
  test:
    description: test
  huancheng:
    description: huancheng
  c:
    description: c
  fixlore:
    description: fixlore
